# https://starship.rs/config/#prompt

# Inserts a blank line between shell prompts
add_newline = true


format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$nodejs\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character\
"""

# https://starship.rs/config/#directory
[directory]
truncate_to_repo = false

[git_branch]
symbol = " "

[git_state]
cherry_pick = "[🍒 PICKING](bold red)"
merge =" MERGING"
revert ="碑 REVERTING"
rebase ="REBASING"
bisect ="BISECTING"

[nodejs]
version_format = "$raw"

[package]
version_format = "$raw"
display_private = true
