tap "homebrew/bundle"
brew "antibody" # Plugin manager for zsh
brew "mas" # Install apps from app store
brew "starship" # Terminal theme
brew "zsh"
brew "git"
brew "gnupg"

# Essentials
brew "fzf" # It's an interactive Unix filter for command-line.
brew "nvm"
brew "pnpm"
cask "arc"
cask "aldente" # set max battery charge
cask "adguard"
cask "figma"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "notion"
cask "raycast"
cask "shottr"
cask "spotify"
cask "visual-studio-code"
cask "warp"
mas "Hidden Bar", id: 1452453066
mas "Slack", id: 803453959
mas "Spark Desktop", id: 6445813049
mas "Velja", id: 1607635845 # Default browser per link

# Useful when needed
brew "awscli"
brew "bat" # Like cat, but better
brew "vim"
cask "firefox@developer-edition"
cask "iina"
brew "jq" # JSON processor
cask "kap"
cask "postman"
cask "proxyman"
cask "sublime-text"
cask "tableplus"
mas "iStat Menus", id: 1319778037
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Vidimote", id: 1585702412 # For Safari

# Not using often
brew "fd" # Intuitive find CLI
brew "fx" # Json Viewer https://github.com/antonmedv/fx
brew "gh"
brew "pstree"
brew "tldr" # better than man command
cask "brave-browser"
cask "discord"
cask "drawio"
cask "stremio"
cask "tradingview"
mas "Kindle", id: 302584613
mas "Telegram", id: 747648890
mas "WhatsApp", id: 310633997

# Testing
mas "ScreenBrush", id: 1233965871
mas "Image2Icon", id: 992115977
